# Generated by Django 3.0.5 on 2022-10-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8, unique=True)),
                ('brand', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
