# Generated by Django 4.1 on 2022-10-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
