# Generated by Django 3.0.5 on 2022-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_catalog', '0002_alter_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='imagen',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
