# Generated by Django 4.1 on 2022-10-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_catalog', '0003_auto_20221012_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagen',
            field=models.ImageField(default='null', upload_to='autos', verbose_name='miniatura'),
        ),
    ]
